### ISSUE TITLE
First call to Analyze Images always fails and the subsequent call  succeeds.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#956]
**Steps to reproduce the problem:**
1. Chat with `obot` and ask to `generate an image`
2. Once image is generated , ask to `describe this image as a pirate would do`

Notice that there are 2 tool calls to ` Analyze Images` being made.

<img width="561" alt="Screenshot 2024-12-18 at 11 31 28 AM" src="https://github.com/user-attachments/assets/24f35caa-13cd-4f87-9e91-1f9d802afb5c" />

tool calls from debug logs:
```
          {
            "content": "",
            "role": "assistant",
            "tool_calls": [
              {
                "function": {
                  "arguments": "{\"images\":\"generated_image_a9dcd4d9.webp\",\"prompt\":\"Describe this image as a pirate would.\"}",
                  "name": "analyzeImages"
                },
                "id": "call_qsiveMepng2Sm8SZatKEk40M",
                "type": "function"
              }
            ]
          },
          {
            "content": "ERROR: got (exit status 1) while running tool, OUTPUT: file:///obot-tools/images/src/analyze.ts:17\n        throw new Error('Failed to parse images, expected a JSON array of strings');\n              ^\n\nError: Failed to parse images, expected a JSON array of strings\n    at analyzeImages (file:///obot-tools/images/src/analyze.ts:17:15)\n    at file:///obot-tools/images/src/tools.ts:11:13\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:98:5)\n\nNode.js v23.4.0\n",
            "name": "analyzeImages",
            "role": "tool",
            "tool_call_id": "call_qsiveMepng2Sm8SZatKEk40M"
          },
          {
            "content": "",
            "role": "assistant",
            "tool_calls": [
              {
                "function": {
                  "arguments": "{\"images\":[\"generated_image_a9dcd4d9.webp\"],\"prompt\":\"Describe this image as a pirate would.\"}",
                  "name": "analyzeImages"
                },
                "id": "call_JVnv7d7oJ4SdJH3Ymm0ljhgI",
                "type": "function"
              }
            ]
          },
          {
            "content": "Arrr, behold this mighty beast standin’ tall in a sea o’ green, like a guardian o’ the grassy plains! The sky be painted with clouds as fluffy as the finest sails on a pirate ship. This giant bovine beauty gazes yonder, as though searchin’ fer hidden treasures beneath the billowin’ skies. Aye, her shadow be cast long and strong, like the shadow of a legendary sea monster! Ye can almost hear the whispers o’ the wind tellin’ tales of adventures untold. Yarrr!",
            "name": "analyzeImages",
            "role": "tool",
            "tool_call_id": "call_JVnv7d7oJ4SdJH3Ymm0ljhgI"
          }
        ],
        "model": "llm",
```

debug logs - 
[calls (61).json](https://github.com/user-attachments/files/18188064/calls.61.json)

**Comment by cjellick** [comment]
Perhaps the images param could accept either an array or single string.
